topics:
 -
     topic: /odom 
     type: nav_msgs/msg/Odometry
     queue_size: 100
 -
     topic: /cmd_vel
     type: geometry_msgs/msg/Twist
     queue_size: 10
 -
     topic: /scan
     type: sensor_msgs/msg/LaserScan
     queue_size: 100
services_2_to_1:
 []
services_1_to_2:
 []